"""Precompute SONAR embeddings on the local venv (where fairseq2 already works)
so the Colab notebook can skip the entire fairseq2/sonar-space/transformers
dependency chain. Generates:

  data_for_colab/sonar_corpus_2000.npy        (N_sentences x 1024 float32)
  data_for_colab/sonar_corpus_2000_meta.json  ({"sentence_to_parent": [...], ...})
  data_for_colab/sonar_test_queries_50.npy    (50 x 1024 float32)
  data_for_colab/manifest.json                (versions + shapes for sanity)

Corpus encoding is the slow step (~30-60 min on CPU for 14k sentences).
Test queries are negligible (~10s).
"""
import json, time
from pathlib import Path

import numpy as np
import nltk
from nltk.tokenize import sent_tokenize
from datasets import load_dataset
from sonar.inference_pipelines.text import TextToEmbeddingModelPipeline

CORPUS_SIZE = 2000
N_TEST      = 50
SEED        = 42

OUT_DIR = Path("data_for_colab")
OUT_DIR.mkdir(exist_ok=True)

ds = load_dataset("casehold/casehold", "all")
train = ds["train"].select(range(CORPUS_SIZE))
test  = ds["test"].select(range(N_TEST))
corpus_texts = [r["citing_prompt"] for r in train]
test_queries = [r["citing_prompt"] for r in test]
print(f"corpus_texts: {len(corpus_texts)}  test_queries: {len(test_queries)}")

nltk.download("punkt_tab", quiet=True); nltk.download("punkt", quiet=True)

corpus_sentences, sentence_to_parent = [], []
for i, t in enumerate(corpus_texts):
    for s in sent_tokenize(t):
        s = s.strip()
        if len(s) > 10:
            corpus_sentences.append(s); sentence_to_parent.append(i)
print(f"segmented {len(corpus_texts)} excerpts -> {len(corpus_sentences)} sentences")

print("loading SONAR encoder...")
t0 = time.time()
sonar = TextToEmbeddingModelPipeline(
    encoder="text_sonar_basic_encoder",
    tokenizer="text_sonar_basic_encoder",
)
print(f"SONAR loaded in {time.time()-t0:.0f}s")

# --- corpus encoding ---
corpus_npy = OUT_DIR / f"sonar_corpus_{CORPUS_SIZE}.npy"
meta_path  = OUT_DIR / f"sonar_corpus_{CORPUS_SIZE}_meta.json"

if corpus_npy.exists():
    sent_vec = np.load(corpus_npy)
    print(f"loaded cached corpus embeddings {sent_vec.shape}")
else:
    print(f"encoding {len(corpus_sentences)} corpus sentences in chunks of 500...")
    t0 = time.time(); chunks = []
    for start in range(0, len(corpus_sentences), 500):
        batch = corpus_sentences[start:start+500]
        v = sonar.predict(batch, source_lang="eng_Latn", batch_size=16).numpy().astype("float32")
        chunks.append(v)
        elapsed = time.time() - t0
        rate = (start + len(batch)) / elapsed if elapsed > 0 else 0
        eta = (len(corpus_sentences) - (start + len(batch))) / rate if rate > 0 else 0
        print(f"  {start+len(batch)}/{len(corpus_sentences)}  ({elapsed:.0f}s, ETA {eta:.0f}s)", flush=True)
    sent_vec = np.concatenate(chunks, axis=0)
    np.save(corpus_npy, sent_vec)
    print(f"encoded in {time.time()-t0:.0f}s, saved {corpus_npy}")

meta = {
    "corpus_size": CORPUS_SIZE,
    "n_sentences": len(corpus_sentences),
    "sentence_to_parent": sentence_to_parent,
    "embedding_dim": int(sent_vec.shape[1]),
    "encoder": "text_sonar_basic_encoder",
}
meta_path.write_text(json.dumps(meta))
print(f"wrote {meta_path} ({meta_path.stat().st_size // 1024} KB)")

# --- test query encoding ---
queries_npy = OUT_DIR / f"sonar_test_queries_{N_TEST}.npy"
if queries_npy.exists():
    qv = np.load(queries_npy)
    print(f"loaded cached query embeddings {qv.shape}")
else:
    print(f"encoding {N_TEST} test queries...")
    t0 = time.time()
    qv = sonar.predict(test_queries, source_lang="eng_Latn", batch_size=16).numpy().astype("float32")
    np.save(queries_npy, qv)
    print(f"encoded in {time.time()-t0:.0f}s, saved {queries_npy} {qv.shape}")

# --- manifest for sanity ---
manifest = {
    "seed": SEED,
    "corpus_size": CORPUS_SIZE,
    "n_test": N_TEST,
    "encoder": "text_sonar_basic_encoder",
    "corpus_npy": corpus_npy.name,
    "corpus_npy_bytes": corpus_npy.stat().st_size,
    "corpus_npy_shape": list(sent_vec.shape),
    "corpus_meta_json": meta_path.name,
    "queries_npy": queries_npy.name,
    "queries_npy_bytes": queries_npy.stat().st_size,
    "queries_npy_shape": list(qv.shape),
    "note": "Generated by precompute_for_colab.py on the local venv. The Colab notebook downloads these instead of installing fairseq2.",
}
(OUT_DIR / "manifest.json").write_text(json.dumps(manifest, indent=2))
print(f"\nmanifest:\n{json.dumps(manifest, indent=2)}")
